import { StartupOverview, ProductSpec, StartupInput } from '@/types';

const MINIMAX_API_URL = 'https://api.minimax.chat/v1/text/chatcompletion_pro';
const MINIMAX_API_KEY = process.env.MINIMAX_API_KEY || '';
const GEMINI_API_KEY = process.env.GEMINI_API_KEY || '';
const GEMINI_API_URL = 'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent';

export interface AIResponse {
  content: string;
  model: 'minimax' | 'gemini' | 'fallback';
  error?: string;
}

export async function callMinimaxChat(messages: Array<{ role: string; content: string }>): Promise<string> {
  if (!MINIMAX_API_KEY) {
    throw new Error('MINIMAX_API_KEY not configured');
  }

  const formattedMessages = messages.map((msg) => ({
    role: msg.role === 'cto' || msg.role === 'assistant' ? 'assistant' : msg.role,
    content: msg.content
  }));

  const models = ['MiniMax-M2.7', 'MiniMax-M2.5', 'MiniMax-Text-01'];
  let lastError = '';

  for (const model of models) {
    try {
      const response = await fetch(MINIMAX_API_URL, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${MINIMAX_API_KEY}`,
        },
        body: JSON.stringify({
          model: model,
          tokens_to_generate: 2048,
          temperature: 0.8,
          messages: formattedMessages
        }),
      });

      if (response.ok) {
        const data = await response.json();
        const content = data.choices?.[0]?.messages?.[0]?.text ||
          data.choices?.[0]?.message?.content ||
          data.choices?.[0]?.text || '';

        if (content) {
          return content;
        }
      }
      lastError = `Model ${model} failed: ${response.status}`;
    } catch (e) {
      lastError = `Model ${model} error: ${e instanceof Error ? e.message : 'Unknown error'}`;
    }
  }

  throw new Error(lastError || 'All MiniMax models failed');
}

export async function callGeminiChat(messages: Array<{ role: string; content: string }>): Promise<string> {
  if (!GEMINI_API_KEY) {
    throw new Error('GEMINI_API_KEY not configured');
  }

  const GEMINI_CHAT_URL = 'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent';

  const contents = messages.map((msg) => ({
    role: msg.role === 'user' ? 'user' : 'model',
    parts: [{ text: msg.content }]
  }));

  const response = await fetch(`${GEMINI_CHAT_URL}?key=${GEMINI_API_KEY}`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ contents })
  });

  if (!response.ok) {
    const error = await response.text();
    throw new Error(`Gemini API error: ${response.status} - ${error}`);
  }

  const data = await response.json();
  const text = data.candidates?.[0]?.content?.parts?.[0]?.text || '';

  if (!text) {
    throw new Error('Empty response from Gemini');
  }

  return text;
}

// Super-Agent Synthesis Function
export async function generateSynthesizedMasterplan(userContext: Partial<any>): Promise<{ content: string, model: string }> {
  const prompt = `Act as an expert CTO. Generate a comprehensive, 10-section Masterplan markdown document based on these startup details:
- Idea: ${userContext.idea || 'N/A'}
- Target Audience: ${userContext.targetAudience || 'N/A'}
- Platform: ${userContext.platform || 'N/A'}
- MVP Features: ${userContext.features || 'N/A'}
- Tech Stack: ${userContext.techStack || 'N/A'}
- Challenges: ${userContext.challenges || 'N/A'}

Include App Overview, Target Audience, Core Features, Tech Stack, Data Models, UI Principles, Security, Milestones, Challenges, and Future Expansion. Do NOT just repeat inputs; add deep engineering insight.`;

  const dummyMessages = [{ role: 'user', content: prompt }];
  let minimaxDraft = '';
  let geminiDraft = '';

  // 1. Concurrently fetch deep structural drafts from both models
  try {
    const [mDraft, gDraft] = await Promise.allSettled([
      callMinimaxChat(dummyMessages),
      callGeminiChat(dummyMessages)
    ]);
    if (mDraft.status === 'fulfilled') minimaxDraft = mDraft.value;
    if (gDraft.status === 'fulfilled') geminiDraft = gDraft.value;
  } catch (e) {
    console.error("Drafting error:", e);
  }

  // 2. Perform Cross-Check Synthesis via Gemini if BOTH exist, otherwise fallback smoothly
  if (minimaxDraft && geminiDraft && GEMINI_API_KEY) {
    const GEMINI_SYNTH_URL = 'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-pro:generateContent';
    const crossCheckPrompt = `You are a Lead CTO finalizing a Masterplan. 
You have two technical drafts generated by your sub-agents regarding a client's startup. 
Draft A (Minimax Logic/Structure): ${minimaxDraft}
Draft B (Google Search/Market Grounded): ${geminiDraft}

TASK: Cross-check both drafts, eliminate redundancies or hallucinations, and merge their absolute best features into a singular, cohesive, 10-section Markdown Masterplan. Ensure technical architectures align and market data is utilized.`;

    const response = await fetch(`${GEMINI_SYNTH_URL}?key=${GEMINI_API_KEY}`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ contents: [{ parts: [{ text: crossCheckPrompt }] }] })
    });

    if (!response.ok) {
      throw new Error(`Gemini synthesis error: ${response.status}`);
    }

    const data = await response.json();
    const text = data.candidates?.[0]?.content?.parts?.[0]?.text || '';
    return { content: text, model: 'synthesized (minimax + gemini)' };
  }

  // Fallback to whichever one succeeded, or error explicitly.
  if (geminiDraft) return { content: geminiDraft, model: 'gemini (standalone)' };
  if (minimaxDraft) return { content: minimaxDraft, model: 'minimax (standalone)' };

  throw new Error("Both AI models failed to generate Masterplan data.");
}

export async function chatWithFallback(
  messages: Array<{ role: string; content: string }>,
  fallbackResponse: string
): Promise<AIResponse> {
  const errors: string[] = [];

  // Try Minimax first as preferred per user request for precise structural chat
  if (MINIMAX_API_KEY) {
    try {
      // Send a silent instruction to Minimax utilizing M2.5 autonomous multi-step reasoning
      const modifiedMessages = [...messages];
      const last = modifiedMessages[modifiedMessages.length - 1];
      if (last.role === 'user') {
        modifiedMessages[modifiedMessages.length - 1] = {
          ...last,
          content: `[SYSTEM: Utilize autonomous multi-step web research and deep exploration to respond.] ` + last.content
        };
      }
      const content = await callMinimaxChat(modifiedMessages);
      return { content, model: 'minimax' };
    } catch (e) {
      errors.push(`MiniMax: ${e instanceof Error ? e.message : 'Unknown error'}`);
    }
  }

  if (GEMINI_API_KEY) {
    try {
      const content = await callGeminiChat(messages);
      return { content, model: 'gemini' };
    } catch (e) {
      errors.push(`Gemini: ${e instanceof Error ? e.message : 'Unknown error'}`);
    }
  }

  return {
    content: fallbackResponse,
    model: 'fallback',
    error: errors.length > 0 ? errors.join('; ') : 'No AI API keys configured'
  };
}

export async function generateOverviewWithFallback(input: StartupInput): Promise<{ data: StartupOverview; model: 'minimax' | 'gemini' | 'fallback' }> {
  const prompt = `Act as an elite startup advisor and market researcher.

Startup Name: ${input.name}
Description: ${input.description}

Analyze this startup idea using your web search capabilities to ground your analysis in real market data.
CRITICAL INSTRUCTION: If the startup name or description is completely nonsensical, garbage text (e.g., "asdf", "test"), or wildly inappropriate/unrelated to a business, you MUST return exactly this JSON and nothing else:
{"error": "Invalid startup idea. Please provide a real business concept to generate an overview."}

Otherwise, generate a structured startup analysis in JSON format with these exact fields:
1. problemStatement - (string) clear description of the problem being solved, grounded in real market data
2. targetAudience - (string) who is this for (demographics, behaviors, pain points) as a single string
3. marketOpportunity - (string) brief real-world market size and opportunity based on search data
4. monetizationStrategy - (string) how will this make money, referencing similar successful models
5. mvpFeatures - (array of strings) array of 5-6 key features for MVP (bullet points)
6. feasibilityScore - (number) number 1-10 rating based on market saturation
7. oneLinePitch - (string) compelling one-sentence pitch

Return ONLY valid JSON, no markdown or extra text.`;

  const systemPrompt = 'You are a helpful assistant that responds in JSON format only.';
  const fallbackData: StartupOverview = {
    problemStatement: `Users struggle with ${input.description || 'the challenge mentioned'}`,
    targetAudience: 'Early adopters, tech-savvy professionals aged 25-45',
    marketOpportunity: 'Growing market with significant untapped potential',
    monetizationStrategy: 'Freemium model with premium features',
    mvpFeatures: [
      'User authentication and profile management',
      'Core functionality dashboard',
      'Basic analytics and reporting',
      'Email notifications',
      'Mobile responsive design'
    ],
    feasibilityScore: 7,
    oneLinePitch: `${input.name} helps users achieve more with less effort`
  };

  const errors: string[] = [];

  if (MINIMAX_API_KEY) {
    const models = ['MiniMax-M2.7', 'MiniMax-M2.5', 'MiniMax-Text-01'];

    for (const model of models) {
      try {
        const response = await fetch(MINIMAX_API_URL, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'Authorization': `Bearer ${MINIMAX_API_KEY}`,
          },
          body: JSON.stringify({
            model: model,
            tokens_to_generate: 1024,
            temperature: 0.7,
            messages: [
              { role: 'system', content: systemPrompt },
              { role: 'user', content: prompt }
            ]
          }),
        });

        if (response.ok) {
          const data = await response.json();
          const content = data.choices?.[0]?.messages?.[0]?.text ||
            data.choices?.[0]?.message?.content ||
            data.choices?.[0]?.text || '';
          if (content) {
            try {
              const parsed = JSON.parse(content);
              if (parsed.error) throw new Error(parsed.error);
              return { data: parsed, model: 'minimax' };
            } catch (e) {
              console.error(`Failed to parse MiniMax ${model} response or invalid idea:`, e);
              if (e instanceof Error && e.message.includes('Invalid startup idea')) throw e;
            }
          }
        } else {
          errors.push(`MiniMax ${model}: HTTP ${response.status}`);
        }
      } catch (e) {
        const error = e instanceof Error ? e.message : 'Unknown error';
        errors.push(`MiniMax ${model}: ${error}`);
      }
    }
  }

  if (GEMINI_API_KEY) {
    try {
      const GEMINI_JSON_URL = 'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent';
      const response = await fetch(`${GEMINI_JSON_URL}?key=${GEMINI_API_KEY}`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          contents: [{ parts: [{ text: `${systemPrompt}\n\n${prompt}` }] }],
          tools: [{ googleSearch: {} }]
        })
      });

      if (response.ok) {
        const data = await response.json();
        const text = data.candidates?.[0]?.content?.parts?.[0]?.text || '';

        if (text) {
          const cleaned = text.replace(/```json\n?/g, '').replace(/```\n?/g, '').trim();
          try {
            const parsed = JSON.parse(cleaned);
            if (parsed.error) throw new Error(parsed.error);
            return { data: parsed, model: 'gemini' };
          } catch (e) {
            console.error('Failed to parse Gemini response or invalid idea:', e);
            if (e instanceof Error && e.message.includes('Invalid startup idea')) throw e;
          }
        }
      } else {
        errors.push(`Gemini: HTTP ${response.status}`);
      }
    } catch (e) {
      const error = e instanceof Error ? e.message : 'Unknown error';
      errors.push(`Gemini: ${error}`);
    }
  }

  if (errors.length > 0) {
    console.error('AI generation errors:', errors);
  }

  return { data: fallbackData, model: 'fallback' };
}

export async function generateProductSpecWithFallback(
  overview: StartupOverview,
  startupName: string
): Promise<{ data: ProductSpec; model: 'minimax' | 'gemini' | 'fallback' }> {
  const prompt = `Act as a senior product manager.

Based on this startup:
Name: ${startupName}
Problem: ${overview.problemStatement}
Target Audience: ${overview.targetAudience}
MVP Features: ${overview.mvpFeatures.join(', ')}

Generate a full product specification in JSON format with these exact fields:
1. coreFeatures - (array of strings) array of 6-8 key product features
2. pages - (array of objects) array of page objects with "name" (string), "purpose" (string), and "keyElements" (array of strings)
3. userFlow - (array of strings) array of steps for user journey
4. techStack - (object) object with "frontend" (string), "backend" (string), "database" (string), "deployment" (string) suggestions
5. scalingConsiderations - (string) brief notes on how to scale

Return ONLY valid JSON, no markdown or extra text.`;

  const systemPrompt = 'You are a helpful assistant that responds in JSON format only.';
  const fallbackData: ProductSpec = {
    coreFeatures: [
      'User authentication and onboarding',
      'Interactive dashboard with real-time data',
      'Search and filtering capabilities',
      'User settings and preferences',
      'Analytics and insights',
      'Notification system'
    ],
    pages: [
      { name: 'Landing Page', purpose: 'First impression and value proposition', keyElements: ['Hero section', 'Features overview', 'CTA'] },
      { name: 'Dashboard', purpose: 'Main workspace for users', keyElements: ['Quick stats', 'Recent activity', 'Quick actions'] },
      { name: 'Settings', purpose: 'User preferences management', keyElements: ['Profile', 'Notifications', 'Privacy'] }
    ],
    userFlow: ['Sign up → Onboarding → Dashboard → Use features → Track progress'],
    techStack: {
      frontend: 'Next.js + Tailwind CSS',
      backend: 'Node.js with Express',
      database: 'PostgreSQL',
      deployment: 'Vercel'
    },
    scalingConsiderations: 'Consider microservices architecture and CDN for assets'
  };

  const errors: string[] = [];

  if (MINIMAX_API_KEY) {
    const models = ['MiniMax-M2.7', 'MiniMax-M2.5', 'MiniMax-Text-01'];

    for (const model of models) {
      try {
        const response = await fetch(MINIMAX_API_URL, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'Authorization': `Bearer ${MINIMAX_API_KEY}`,
          },
          body: JSON.stringify({
            model: model,
            tokens_to_generate: 1024,
            temperature: 0.7,
            messages: [
              { role: 'system', content: systemPrompt },
              { role: 'user', content: prompt }
            ]
          }),
        });

        if (response.ok) {
          const data = await response.json();
          const content = data.choices?.[0]?.messages?.[0]?.text ||
            data.choices?.[0]?.message?.content ||
            data.choices?.[0]?.text || '';
          if (content) {
            try {
              return { data: JSON.parse(content), model: 'minimax' };
            } catch (e) {
              console.error(`Failed to parse MiniMax ${model} response as JSON:`, e);
            }
          }
        } else {
          errors.push(`MiniMax ${model}: HTTP ${response.status}`);
        }
      } catch (e) {
        const error = e instanceof Error ? e.message : 'Unknown error';
        errors.push(`MiniMax ${model}: ${error}`);
      }
    }
  }

  if (GEMINI_API_KEY) {
    try {
      const GEMINI_JSON_URL = 'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent';
      const response = await fetch(`${GEMINI_JSON_URL}?key=${GEMINI_API_KEY}`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          contents: [{ parts: [{ text: `${systemPrompt}\n\n${prompt}` }] }]
        })
      });

      if (response.ok) {
        const data = await response.json();
        const text = data.candidates?.[0]?.content?.parts?.[0]?.text || '';

        if (text) {
          const cleaned = text.replace(/```json\n?/g, '').replace(/```\n?/g, '').trim();
          try {
            return { data: JSON.parse(cleaned), model: 'gemini' };
          } catch {
            console.error('Failed to parse Gemini response as JSON');
          }
        }
      } else {
        errors.push(`Gemini: HTTP ${response.status}`);
      }
    } catch (e) {
      const error = e instanceof Error ? e.message : 'Unknown error';
      errors.push(`Gemini: ${error}`);
    }
  }

  if (errors.length > 0) {
    console.error('AI generation errors:', errors);
  }

  return { data: fallbackData, model: 'fallback' };
}
